// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAffwxyc4e9vU85WtiMJyWRR5w7whPaGVo',
    appId: '1:59207002899:web:eaeb5bbd1010bc75e648e6',
    messagingSenderId: '59207002899',
    projectId: 'nfcproj-6ebf6',
    authDomain: 'nfcproj-6ebf6.firebaseapp.com',
    storageBucket: 'nfcproj-6ebf6.firebasestorage.app',
    measurementId: 'G-MRFGFNRB6C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVxrYDXc2fqTtbiI8WEqxt1Si_xNc7Gu8',
    appId: '1:59207002899:android:97a5049df8b02ac7e648e6',
    messagingSenderId: '59207002899',
    projectId: 'nfcproj-6ebf6',
    storageBucket: 'nfcproj-6ebf6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHSn_IJw0_YTLYT-N15HB1LnmNMu3vsu4',
    appId: '1:59207002899:ios:243109cbc3d07fb9e648e6',
    messagingSenderId: '59207002899',
    projectId: 'nfcproj-6ebf6',
    storageBucket: 'nfcproj-6ebf6.firebasestorage.app',
    iosBundleId: 'com.example.learning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHSn_IJw0_YTLYT-N15HB1LnmNMu3vsu4',
    appId: '1:59207002899:ios:243109cbc3d07fb9e648e6',
    messagingSenderId: '59207002899',
    projectId: 'nfcproj-6ebf6',
    storageBucket: 'nfcproj-6ebf6.firebasestorage.app',
    iosBundleId: 'com.example.learning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAffwxyc4e9vU85WtiMJyWRR5w7whPaGVo',
    appId: '1:59207002899:web:f3d2d9c2ad976cc6e648e6',
    messagingSenderId: '59207002899',
    projectId: 'nfcproj-6ebf6',
    authDomain: 'nfcproj-6ebf6.firebaseapp.com',
    storageBucket: 'nfcproj-6ebf6.firebasestorage.app',
    measurementId: 'G-9XKXYRTPNE',
  );
}
